`uniffi::remote(Enum)` needs `derive(uniffi::Enum)`, requiring `Arc`
If we switch the inner type to `uniffi::remote(Enum)` it only works if
we switch the holding type to `derive(uniffi::Enum)` (rather than
defining in UDL). This in turn will require the Rust API to return the
`Arc`-wrapped `Arc<TypeHoldingClosureReason>` where previously it could
just return `TypeHoldingClosureReason` and `uniffi` did the wrapping
automatically.

```
> cargo build
   Compiling uniffi-remote-interface-29 v0.1.0 (/home/tnull/workspace/uniffi-remote-interface-29)
error[E0277]: the trait bound `TypeHoldingClosureReason: FfiConverterArc<UniFfiTag>` is not satisfied
  --> /home/tnull/workspace/uniffi-remote-interface-29/target/debug/build/uniffi-remote-interface-29-448d9dd4cf866cdd/out/test.uniffi.rs:45:1
   |
45 | #[::uniffi::export_for_udl]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ unsatisfied trait bound
   |
help: the trait `FfiConverterArc<UniFfiTag>` is not implemented for `TypeHoldingClosureReason`
  --> src/lib.rs:18:1
   |
18 | pub enum TypeHoldingClosureReason {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: the trait `LowerReturn<UT>` is implemented for `Arc<T>`
   = note: required for `Arc<TypeHoldingClosureReason>` to implement `FfiConverter<UniFfiTag>`
   = note: required for `Arc<TypeHoldingClosureReason>` to implement `uniffi::Lower<UniFfiTag>`
   = note: required for `Arc<TypeHoldingClosureReason>` to implement `LowerReturn<UniFfiTag>`
   = note: this error originates in the attribute macro `::uniffi::export_for_udl` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `TypeHoldingClosureReason: FfiConverterArc<UniFfiTag>` is not satisfied
  --> /home/tnull/workspace/uniffi-remote-interface-29/target/debug/build/uniffi-remote-interface-29-448d9dd4cf866cdd/out/test.uniffi.rs:45:1
   |
45 | #[::uniffi::export_for_udl]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ unsatisfied trait bound
   |
help: the trait `FfiConverterArc<UniFfiTag>` is not implemented for `TypeHoldingClosureReason`
  --> src/lib.rs:18:1
   |
18 | pub enum TypeHoldingClosureReason {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: the trait `FfiConverter<UT>` is implemented for `Arc<T>`
   = note: required for `Arc<TypeHoldingClosureReason>` to implement `FfiConverter<UniFfiTag>`
   = note: this error originates in the attribute macro `::uniffi::export_for_udl` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /home/tnull/workspace/uniffi-remote-interface-29/target/debug/build/uniffi-remote-interface-29-448d9dd4cf866cdd/out/test.uniffi.rs:45:1
    |
 45 | #[::uniffi::export_for_udl]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | |
    | expected `Arc<TypeHoldingClosureReason>`, found `TypeHoldingClosureReason`
    | arguments to this function are incorrect
    |
    = note: expected struct `Arc<TypeHoldingClosureReason>`
                 found enum `TypeHoldingClosureReason`
help: the return type of this call is `TypeHoldingClosureReason` due to the type of the argument passed
   --> /home/tnull/workspace/uniffi-remote-interface-29/target/debug/build/uniffi-remote-interface-29-448d9dd4cf866cdd/out/test.uniffi.rs:45:1
    |
 45 | #[::uniffi::export_for_udl]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ this argument influences the return type of `lower_return`
note: associated function defined here
   --> /home/tnull/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uniffi_core-0.29.5/src/ffi_converter_traits.rs:296:8
    |
296 |     fn lower_return(v: Self) -> Result<Self::ReturnType, RustCallError>;
    |        ^^^^^^^^^^^^
    = note: this error originates in the attribute macro `::uniffi::export_for_udl` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Signed-off-by: Elias Rohrer <dev@tnull.de>